site_name: "UCS503 : Campus Feedback System (TechNova)"
site_url: https://kchhabra777.github.io/campus-feedback-system

plugins:
  - search
  - literate-nav:
      nav_file: summary.md
  - section-index
  - git-revision-date-localized
  - git-authors

theme:
  name: material
  custom_dir: docs/assets/theme-overrides
  features:
    - navigation.footer
    - header.autohide
    - content.tabs.link
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - content.tooltips
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle-outline
  palette:
    primary: amber
    accent: orange
  logo: assets/tiet-mark.png
  favicon: assets/favicon.png

repo_url: https://github.com/kchhabra777/campus-feedback-system
repo_name: campus-feedback-system
copyright: "Copyright &copy; 2026 TechNova (3Q1A) &lt;<code>TIET Patiala</code>&gt;"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kchhabra777/campus-feedback-system
      name: Git Repo for Campus Feedback System

extra_css:
  - assets/stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - javascript/arithmatex.js

markdown_extensions:
  - abbr
  - md_in_html
  - attr_list
  - toc:
      permalink: true
      toc_depth: 4
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {which: generic}
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          arithmatex: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {which: generic}
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - sane_lists
